// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKUzmEBYt39gqSeKbQxYeKd-xAYhI1-g',
    appId: '1:154735310163:web:4d7b66b600a4520ef7dda6',
    messagingSenderId: '154735310163',
    projectId: 'auth-557f9',
    authDomain: 'auth-557f9.firebaseapp.com',
    storageBucket: 'auth-557f9.firebasestorage.app',
    measurementId: 'G-MZTMV1BPJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgXnc5DinJ_2-26deyb4jXecq02IyqY3g',
    appId: '1:154735310163:android:2d001fddc9aa21caf7dda6',
    messagingSenderId: '154735310163',
    projectId: 'auth-557f9',
    storageBucket: 'auth-557f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBltRWzXtb0ldIML16niqIHsDXPGU9xN_o',
    appId: '1:154735310163:ios:2987ace08009ae0ff7dda6',
    messagingSenderId: '154735310163',
    projectId: 'auth-557f9',
    storageBucket: 'auth-557f9.firebasestorage.app',
    iosBundleId: 'com.tejavarshith.resumerevive',
  );

}